### ISSUE TITLE
Get image information

### ISSUE THREAD

**Issue by quentinlamamy** [dlemstra/magick-wasm#90]
### Describe the solution you'd like

The method should return image informaiton :
- format
- size
- dimension
- exif

or any information imagemgick can extract

**Comment by dlemstra** [comment]
You can already get `format`, `dimension` and `exif`. And I will not be going to add `size` because you can only read from a byte array at the moment and then you can just do `array.length` to get the size. More information will be added when I have time to work on this project. Feel free to open an issue if you are missing a specific set of information that is available in ImageMagick but not in this library.

**Comment by quentinlamamy** [comment]
will dig the code and wait for doc.
Thks for your work
